project_id = "mepznzrijuoyvjcmkspf"

[functions.admin-auth]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.get-notifications]
verify_jwt = false

[functions.mark-notification-read]
verify_jwt = false

[functions.mark-all-notifications-read]
verify_jwt = false

[functions.publish-scheduled-posts]
verify_jwt = false
